### PR TITLE
Install Script

### PR DESCRIPTION
**Pull request by njaremko**
Not sure if you're hard pressed on piping a file to sh, but if you're not and you're willing to require that users have golang already installed...

Then just get them to execute `wget https://github.com/itsabot/abot/abot_install.go && go run abot_install.go`

The script puts abot in the GOPATH, and runs cmd/setup. If you want it to do more, just let me know.

### CODE REVIEW

**Comment by egtann** [comment]
Hey Nathan, thanks for making this. I would like to have a single installer via sh, though, so I can't merge this in.

Installing Go and Postgres 9.5 seem to be big sticking points for new Abot developers, so the purpose of this install script will be to automate the process with defaults.

**Comment by njaremko** [comment]
No worries, writing  a bash script is just more of a pain in the butt. Anyway, how did you want to handle setting up postgres? You would need to require sudo to run apt-get/yum/pacman, and to enable the systemd job.

**Comment by egtann** [comment]
That's precisely what we'll do. The script is open-source and available for everyone to read before running. I'm taking inspiration Heroku's cli tool install process, which does the same thing.

**Comment by njaremko** [comment]
Ahh, okay then. So what distros did you want to focus on? ubuntu, arch, fedora?

**Comment by egtann** [comment]
Ubuntu and OSX to start.  I assume most people running Arch and Fedora will be able to install the dependencies themselves, whereas Ubuntu seems to be the "starter" distro.

**Comment by njaremko** [comment]
Are we assuming they have homebrew installed on OSX?

**Comment by egtann** [comment]
Heroku uses an actual installer for OSX. I'm not sure of the pros/cons with that approach on the platform, so it's worth some research. We probably should not assume that another dependency, eg Homebrew, is installed.

**Comment by njaremko** [comment]
K, I have a script for ubuntu done. Only question, is if we're installing golang for them, where do we put their GOPATH?

**Comment by egtann** [comment]
That's a great question. We could either prompt the user with a sensible default (~/go) or place it there if and only if the directory doesn't exist. It's easy enough for the user to change after-the-fact, too.

**Comment by njaremko** [comment]
Here's the install script for Ubuntu.

The workflow for installing would be:
 `wget <url>`
`source ./install.sh`

**Comment by egtann** [comment]
@njaremko are you sure the .sh was committed? I only see an empty commit.

**Comment by njaremko** [comment]
Yeah it's install.sh in the root of the project.

**Comment by egtann** [comment]
This is a good start. A few notes:

* Can we eliminate setting a password for Postgres altogether? If we eliminate the password I believe you can just call cmd/setup.sh without any args, since everything will use the default settings.
* The script doesn't need to run `go get ...glock`. That happens in cmd/setup.sh.
* I'm still weighing whether we should be installing homebrew on Mac.

**Comment by njaremko** [comment]
- I set a password in postgres for security reasons, but if you think people will only use this script for local stuff then I guess we could remove it. 
- If you don't `go get ...glock` you get an error saying glock isn't installed...so might wanna look into that hahaha
- Yeah, but it's the only way to have an install script on mac, otherwise we'll have to look into an actual installer.

**Comment by egtann** [comment]
That's absolutely a reasonable approach for Mac, especially since the Ruby VM is installed by default in OSX. I'll test out the script, and if all's good, we'll get this merged!

**Comment by njaremko** [comment]
Need to set a postgres password or it won't connect. So I've added it back in.

**Comment by njaremko** [comment]
@egtann is that gpg key that is causing builds to fail yours?

Because if it is, you should submit it to: https://pgp.mit.edu/ to fix this.

**Comment by njaremko** [comment]
Any status updates?

**Comment by egtann** [comment]
Yup. This'll be the final piece I handle with the v0.2 release. We're quickly approaching it, though!

In the end it'll have to be available via itsabot.org/install.sh, so you might want to move the PR over to the itsabot.org repo. Along with it, it'd be helpful to create a handler that serves the static file at that URL.

**Pull request closed without merging**
