### PR TITLE
Email driver for receiving and sending emails

### PR DESCRIPTION
**Pull request by DaleWebb**
Created email interface, similar to the SMS interface, that can receive and send emails.

Implemented with a Mailgun plugin at https://github.com/DaleWebb/mailgun

### CODE REVIEW

**Comment by egtann** [comment]
Brilliant! I'll give it a test.

**Comment by DaleWebb** [comment]
Is the email flex ID supported?  I had some trouble with that

**Comment by egtann** [comment]
It's actually never been used, so I'd guess no. :)  Diving in now.

**Comment by egtann** [comment]
@DaleWebb I think it is working, but you have to switch the FlexIDType to 1. The mailgun route handler you made can set that automatically before having the message be processed.

**Comment by DaleWebb** [comment]
Yeah I switched it to 1 earlier but I expected that the user account I signed up with would have a flex id created for the email address, but it wasn't there.  So I set it to 2 for now and put in a random number so that `core.ProcessText()` would work.

**Comment by egtann** [comment]
Great catch. Just merged a fix for that. #71

**Comment by egtann** [comment]
Looks ready for merge. Could you rebase it into a single commit with the following message (in the imperative tense)? `Add email interface to send and receive emails`

The description below that commit title can go into more detail if you'd like. Then we'll merge it in!

**Comment by DaleWebb** [comment]
Squashed commits

**Comment by egtann** [comment]
Perfect, merged. Many thanks!

**Pull request merged**
