### PR TITLE
Find city when the city is not capitalized

### PR DESCRIPTION
**Pull request by hhsnopek**
Let me know your thoughts and if you'd like anything changed. (currently using the branch locally)

### CODE REVIEW

**Comment by egtann** [comment]
Hey, thanks for handling this!   I think we can make the same change more efficiently, though, if we aim to just modify existing variables.

What if we modified this line 191 as follows? (Haven't tested this. Might not work)

```go
words := strings.Fields(strings.Title(tmp))
```

That way we only have to call the `strings.Title` function once, and we'd eliminate runtime reflection, the additional loop and memory allocation too!

**Comment by hhsnopek** [comment]
Good call, lemme just make sure everything is still working :)

**Comment by hhsnopek** [comment]
👍 updated - note this does not help acronyms like LA: `la -> La`

**Comment by egtann** [comment]
Good point! But I'm pretty sure even a human would have trouble parsing, "how's the weather in la?"  What's "lah?"

Can you rebase into a single commit and force push? It should automatically be reflected in this PR.

**Comment by hhsnopek** [comment]
Whoa where did all those commits come from! Thought I squashed it ha - one sec

**Comment by hhsnopek** [comment]
done 😄

**Comment by egtann** [comment]
Looks great. Thanks! Merging

**Pull request merged**
