### PR TITLE
Loading env variables before plugin is initialised.

### PR DESCRIPTION
**Pull request by ankitbansal82**
This is a possible fix for [#112](https://github.com/itsabot/abot/issues/112)

### CODE REVIEW

**Comment by egtann** [comment]
Since plugins call `New()` on init, I'm pretty sure there's still a race condition. A better approach might be to call LoadEnvVars from within the plugin within `New()` itself prior to using any of them and keep track of when the function has been run, so it doesn't need to run again with, e.g., an `envLoaded` bool set in core.

**Comment by ankitbansal82** [comment]
Ok. In that case i will move LoadEnvVars to shared so both core and plugins can use it.

**Comment by ankitbansal82** [comment]
Done and tested. Please merge back if it looks OK.

**Comment by egtann** [comment]
Just one more correction. LoadEnvVars opens a file and reads its contents. We don't need to run that for every plugin -- we just want it to run once. At the top of `LoadEnvVars` you should check if the env vars have already been loaded with an `envLoaded` bool in shared, and return if they have been. `LoadEnvVars` should set `envLoaded = true`

**Comment by ankitbansal82** [comment]
Ok. Will fix

**Comment by ankitbansal82** [comment]
Done

**Comment by egtann** [comment]
Hey @ankitbansal82, this looks good. Could you squash the commits into a single, well-formatted commit message consistent with the style of our existing commits? Then I'll be able to merge.

**Comment by ankitbansal82** [comment]
@egtann hope this meets the project style template.

**Comment by egtann** [comment]
Much better! Let's just switch it to use an imperative tense verb. `Fix psql connection error on plugin init`

**Comment by ankitbansal82** [comment]
You got a commit template somewhere? So i can get it first time right?

**Comment by egtann** [comment]
It's just an imperative tense verb followed by a brief description.

**Comment by ankitbansal82** [comment]
here you go. I think it will be useful to have a commit template checked in that contributors can use in their git config.
e.g. https://gist.github.com/adeekshith/cd4c95a064977cdc6c50#file-git-commit-template-txt

**Comment by egtann** [comment]
That's a great idea. I'll create a commit template and add it to the wiki.

Also merged! Thanks!

**Comment by egtann** [comment]
FYI, added the commit template to the How to Contribute page here: https://github.com/itsabot/abot/wiki/How-to-Contribute

**Pull request merged**
